#
# Copyright (c) 2022 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_BT=y
CONFIG_LOG=y
CONFIG_BT_DEVICE_NAME="DF Conn App"
CONFIG_BT_SMP=y

CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_APPEARANCE=833

# Disable automatic update of connection parameters
# This option if enabled allows automatically sending request for connection
# parameters update after GAP recommended 5 seconds of connection as
# peripheral.
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n
# This allows to configure peripheral preferred connection parameters.
# Enabling this option results in adding PPCP characteristic in GAP.
# If disabled it is up to application to set expected connection parameters.
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=n

# Enable Direction Finding Feature RX in connected mode
CONFIG_BT_DF=y
CONFIG_BT_DF_CONNECTION_CTE_TX=y
CONFIG_BT_DF_CONNECTION_CTE_RSP=y

# Disable AoD Feature (antenna switching) in Tx mode in Host
CONFIG_BT_DF_CTE_TX_AOD=n
